import ShellDecorator

print(ColorFunc.black("black text"))
print(ColorFunc.red("red text"))
print(ColorFunc.green("green text"))
print(ColorFunc.yellow("yellow text"))
print(ColorFunc.blue("blue text"))
print(ColorFunc.magenta("magenta text"))
print(ColorFunc.cyan("cyan text"))
print(ColorFunc.white("white text"))
print()
print(ColorFunc.black.bold("black bold text"))
print(ColorFunc.red.bold("red bold text"))
print(ColorFunc.green.bold("green bold text"))
print(ColorFunc.yellow.bold("yellow bold text"))
print(ColorFunc.blue.bold("blue bold text"))
print(ColorFunc.magenta.bold("magenta bold text"))
print(ColorFunc.cyan.bold("cyan bold text"))
print(ColorFunc.white.bold("white bold text"))
print()
print(ColorFunc.black.underline("black text with underline"))
print(ColorFunc.red.underline("red text with underline"))
print(ColorFunc.green.underline("green text with underline"))
print(ColorFunc.yellow.underline("yellow text with underline"))
print(ColorFunc.blue.underline("blue text with underline"))
print(ColorFunc.magenta.underline("magenta text with underline"))
print(ColorFunc.cyan.underline("cyan text with underline"))
print(ColorFunc.white.underline("white text with underline"))
print()
print(ColorFunc.black.bold.underline("black bold text with underline"))
print(ColorFunc.red.bold.underline("red bold text with underline"))
print(ColorFunc.green.bold.underline("green bold text with underline"))
print(ColorFunc.yellow.bold.underline("yellow bold text with underline"))
print(ColorFunc.blue.bold.underline("blue bold text with underline"))
print(ColorFunc.magenta.bold.underline("magenta bold text with underline"))
print(ColorFunc.cyan.bold.underline("cyan bold text with underline"))
print(ColorFunc.white.bold.underline("white bold text with underline"))
print()
print(ColorFunc.red.backgroundYellow("red text with yellow background"))
print()
print("default text")
