name: Danger
on:
  pull_request:
    types: [opened, synchronize, edited]
jobs:
  danger:
    name: Danger
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.head_ref }}-${{ github.workflow }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - name: Danger
        uses: 417-72KI/danger-swiftlint@2db57069cf35c1c059a87f7f4a3c5d56ea5c2ed3 # v6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
