name: Danger
on:
  pull_request:
    types: [opened, synchronize, edited]
jobs:
  danger:
    name: Danger
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.head_ref }}-${{ github.workflow }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-${{ hashFiles('Package.swift') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Danger
        uses: 417-72KI/danger-swiftlint@v5.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
